# Generated by Django 6.0.2 on 2026-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_remove_webinar_category_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='webinar_id',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='category',
            field=models.ManyToManyField(to='models.category'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
