# Generated by Django 6.0.2 on 2026-05-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
