# Generated by Django 6.0.2 on 2026-05-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_webinar_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('web-development', 'Web Development'), ('ai-machine-learning', 'AI & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('data-science', 'Data Science'), ('cloud-computing', 'Cloud Computing'), ('business', 'Business'), ('entrepreneurship', 'Entrepreneurship'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('leadership', 'Leadership'), ('education', 'Education'), ('career-growth', 'Career Growth'), ('design', 'Design'), ('ui-ux', 'UI/UX'), ('content-creation', 'Content Creation'), ('health-wellness', 'Health & Wellness'), ('productivity', 'Productivity'), ('gaming', 'Gaming'), ('lifestyle', 'Lifestyle'), ('networking', 'Networking'), ('workshops', 'Workshops'), ('startups', 'Startups'), ('freelancing', 'Freelancing'), ('software-development', 'Software Development')], max_length=20, null=True),
        ),
    ]
