# Generated by Django 6.0.2 on 2026-05-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_alter_category_options_remove_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
